FROM node:18-alpine
RUN apk add --no-cache chromium
WORKDIR /app
COPY worker/package*.json ./
RUN npm ci --production
COPY worker/ ./
ENV CHROME_BIN=/usr/bin/chromium-browser
ENV CHROME_PATH=/usr/lib/chromium/
CMD ["node", "index.js"]
