version: "3.9"

networks:
  hydra-net:
    driver: bridge

services:
  # API1
  api1:
    build:
      context: ./api1
    container_name: hydra-api1
    ports:
      - "41000:4000"
    networks:
      - hydra-net

  # API2
  api2:
    build:
      context: ./api2
    container_name: hydra-api2
    ports:
      - "41001:4001"
    networks:
      - hydra-net

  # API3
  api3:
    build:
      context: ./api3
    container_name: hydra-api3
    ports:
      - "41002:4002"
    networks:
      - hydra-net

  # Website (Nginx + frontend)
  website:
    build:
      context: ./hydra-website
    container_name: hydra-website
    ports:
      - "3000:3000"
    networks:
      - hydra-net
    depends_on:
      - api1
      - api2
      - api3
