services:
  website1:
    build: ./api-catalog/website
    ports:
      - "31000:3000"
    environment:
      - PORT=3000

  website2:
    build: ./api-catalog/website  
    ports:
      - "31001:3000"
    environment:
      - PORT=3000

  website3:
    build: ./api-catalog/website
    ports:
      - "31002:3000"
    environment:
      - PORT=3000

  api1:
    build: ./api-catalog/api
    ports:
      - "41000:4000"
    environment:
      - PORT=4000

  api2:
    build: ./api-catalog/api
    ports:
      - "41001:4000"
    environment:
      - PORT=4000

  api3:
    build: ./api-catalog/api
    ports:
      - "41002:4000"
    environment:
      - PORT=4000

  utm1:
    build: ./api-catalog/utm
    ports:
      - "50000:9000"
    environment:
      - PORT=9000

  utm2:
    build: ./api-catalog/utm
    ports:
      - "50001:9000"
    environment:
      - PORT=9000

  utm3:
    build: ./api-catalog/utm
    ports:
      - "50002:9000"
    environment:
      - PORT=9000
