name: hydra-app
services:
- name: web
  source_dir: /
  dockerfile_path: Dockerfile
  run_command: npm start
  instance_size_slug: basic-xxs
  instance_count: 1
  http_port: 8080
  routes:
  - path: /
