name: hydra-app
services:
- name: web
  image:
    registry_type: DOCKER_HUB
    registry: docker.io
    repository: samw425glitch/hydra-cloud-orchestrator
    tag: latest
  instance_count: 1
  http_port: 8080
  routes:
  - path: /
