name: Docker AutoDeploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker (DigitalOcean registry)
      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCR_USERNAME }}
          password: ${{ secrets.DOCR_ACCESS_TOKEN }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t registry.digitalocean.com/${{ secrets.DOCR_REPO }}/hydra-orchestrator:latest .

      # 4️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push registry.digitalocean.com/${{ secrets.DOCR_REPO }}/hydra-orchestrator:latest

      # 5️⃣ Optional: Trigger DigitalOcean App deployment
      - name: Trigger DigitalOcean App deployment
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: doctl apps update ${{ secrets.DO_APP_ID }} --spec .do/app.yaml
